/*
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Media model module.
 * @module model/Media
 * @version 1.0.0
 */
export class Media {
  /**
   * Constructs a new <code>Media</code>.
   * @alias module:model/Media
   * @class
   * @param mimetype {module:model/Media.MimetypeEnum} Mime type of file
   * @param data {String} Base64 encoded data file body
   * @param filename {String} Name of the file
   */
  constructor(mimetype, data, filename) {
    this.mimetype = mimetype;
    this.data = data;
    this.filename = filename;
  }

  /**
   * Constructs a <code>Media</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Media} obj Optional instance to populate.
   * @return {module:model/Media} The populated <code>Media</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Media();
      if (data.hasOwnProperty('mimetype'))
        obj.mimetype = ApiClient.convertToType(data['mimetype'], 'String');
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], 'String');
      if (data.hasOwnProperty('filename'))
        obj.filename = ApiClient.convertToType(data['filename'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>mimetype</code> property.
 * @enum {String}
 * @readonly
 */
Media.MimetypeEnum = {
  /**
   * value: "application/ogg"
   * @const
   */
  applicationogg: "application/ogg",

  /**
   * value: "application/pdf"
   * @const
   */
  applicationpdf: "application/pdf",

  /**
   * value: "application/zip"
   * @const
   */
  applicationzip: "application/zip",

  /**
   * value: "application/gzip"
   * @const
   */
  applicationgzip: "application/gzip",

  /**
   * value: "application/msword"
   * @const
   */
  applicationmsword: "application/msword",

  /**
   * value: "audio/mp4"
   * @const
   */
  audiomp4: "audio/mp4",

  /**
   * value: "audio/aac"
   * @const
   */
  audioaac: "audio/aac",

  /**
   * value: "audio/mpeg"
   * @const
   */
  audiompeg: "audio/mpeg",

  /**
   * value: "audio/ogg"
   * @const
   */
  audioogg: "audio/ogg",

  /**
   * value: "audio/webm"
   * @const
   */
  audiowebm: "audio/webm",

  /**
   * value: "image/gif"
   * @const
   */
  imagegif: "image/gif",

  /**
   * value: "image/jpeg"
   * @const
   */
  imagejpeg: "image/jpeg",

  /**
   * value: "image/pjpeg"
   * @const
   */
  imagepjpeg: "image/pjpeg",

  /**
   * value: "image/png"
   * @const
   */
  imagepng: "image/png",

  /**
   * value: "image/svg+xml"
   * @const
   */
  imagesvgxml: "image/svg+xml",

  /**
   * value: "image/tiff"
   * @const
   */
  imagetiff: "image/tiff",

  /**
   * value: "image/webp"
   * @const
   */
  imagewebp: "image/webp",

  /**
   * value: "video/mpeg"
   * @const
   */
  videompeg: "video/mpeg",

  /**
   * value: "video/mp4"
   * @const
   */
  videomp4: "video/mp4",

  /**
   * value: "video/ogg"
   * @const
   */
  videoogg: "video/ogg",

  /**
   * value: "video/quicktime"
   * @const
   */
  videoquicktime: "video/quicktime",

  /**
   * value: "video/webm"
   * @const
   */
  videowebm: "video/webm",

  /**
   * value: "video/x-ms-wmv"
   * @const
   */
  videoxMsWmv: "video/x-ms-wmv",

  /**
   * value: "video/x-flv"
   * @const
   */
  videoxFlv: "video/x-flv",

  /**
   * value: "application/vnd.ms-excel"
   * @const
   */
  applicationvndMsExcel: "application/vnd.ms-excel",

  /**
   * value: "application/vnd.ms-powerpoint"
   * @const
   */
  applicationvndMsPowerpoint: "application/vnd.ms-powerpoint",

  /**
   * value: "application/msword"
   * @const
   */
  applicationmsword_26: "application/msword"
};
/**
 * Mime type of file
 * @member {module:model/Media.MimetypeEnum} mimetype
 */
Media.prototype.mimetype = undefined;

/**
 * Base64 encoded data file body
 * @member {String} data
 */
Media.prototype.data = undefined;

/**
 * Name of the file
 * @member {String} filename
 */
Media.prototype.filename = undefined;

