/*
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Media} from './Media';

/**
 * The MessageMedia model module.
 * @module model/MessageMedia
 * @version 1.0.0
 */
export class MessageMedia {
  /**
   * Constructs a new <code>MessageMedia</code>.
   * @alias module:model/MessageMedia
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MessageMedia</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MessageMedia} obj Optional instance to populate.
   * @return {module:model/MessageMedia} The populated <code>MessageMedia</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MessageMedia();
      if (data.hasOwnProperty('body'))
        obj.body = ApiClient.convertToType(data['body'], 'String');
      if (data.hasOwnProperty('quote'))
        obj.quote = ApiClient.convertToType(data['quote'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('media'))
        obj.media = Media.constructFromObject(data['media']);
    }
    return obj;
  }
}

/**
 * @member {String} body
 */
MessageMedia.prototype.body = undefined;

/**
 * @member {String} quote
 */
MessageMedia.prototype.quote = undefined;

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
MessageMedia.TypeEnum = {
  /**
   * value: "image"
   * @const
   */
  image: "image",

  /**
   * value: "sticker"
   * @const
   */
  sticker: "sticker",

  /**
   * value: "doc"
   * @const
   */
  doc: "doc",

  /**
   * value: "voice"
   * @const
   */
  voice: "voice"
};
/**
 * @member {module:model/MessageMedia.TypeEnum} type
 */
MessageMedia.prototype.type = undefined;

/**
 * @member {module:model/Media} media
 */
MessageMedia.prototype.media = undefined;

// Implement AnyOfsendBodyMessage interface:
