/*
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The MessageText model module.
 * @module model/MessageText
 * @version 1.0.0
 */
export class MessageText {
  /**
   * Constructs a new <code>MessageText</code>.
   * @alias module:model/MessageText
   * @class
   * @param body {String} 
   */
  constructor(body) {
    this.body = body;
  }

  /**
   * Constructs a <code>MessageText</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MessageText} obj Optional instance to populate.
   * @return {module:model/MessageText} The populated <code>MessageText</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MessageText();
      if (data.hasOwnProperty('body'))
        obj.body = ApiClient.convertToType(data['body'], 'String');
      if (data.hasOwnProperty('quote'))
        obj.quote = ApiClient.convertToType(data['quote'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} body
 */
MessageText.prototype.body = undefined;

/**
 * @member {String} quote
 */
MessageText.prototype.quote = undefined;

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
MessageText.TypeEnum = {
  /**
   * value: "text"
   * @const
   */
  text: "text"
};
/**
 * @member {module:model/MessageText.TypeEnum} type
 * @default 'text'
 */
MessageText.prototype.type = 'text';

// Implement AnyOfsendBodyMessage interface:
