/*
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RecipientId model module.
 * @module model/RecipientId
 * @version 1.0.0
 */
export class RecipientId {
  /**
   * Constructs a new <code>RecipientId</code>.
   * @alias module:model/RecipientId
   * @class
   * @param id {String} Whatsapp recipient ID with @c.us or @g.us
   */
  constructor(id) {
    this.id = id;
  }

  /**
   * Constructs a <code>RecipientId</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RecipientId} obj Optional instance to populate.
   * @return {module:model/RecipientId} The populated <code>RecipientId</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RecipientId();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
    }
    return obj;
  }
}

/**
 * Whatsapp recipient ID with @c.us or @g.us
 * @member {String} id
 */
RecipientId.prototype.id = undefined;

// Implement AnyOfseenBodyRecipient interface:
// Implement AnyOfsendBodyRecipient interface:
