/*
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ResponseChatGroupMetadataParticipants model module.
 * @module model/ResponseChatGroupMetadataParticipants
 * @version 1.0.0
 */
export class ResponseChatGroupMetadataParticipants {
  /**
   * Constructs a new <code>ResponseChatGroupMetadataParticipants</code>.
   * @alias module:model/ResponseChatGroupMetadataParticipants
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ResponseChatGroupMetadataParticipants</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResponseChatGroupMetadataParticipants} obj Optional instance to populate.
   * @return {module:model/ResponseChatGroupMetadataParticipants} The populated <code>ResponseChatGroupMetadataParticipants</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ResponseChatGroupMetadataParticipants();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('isAdmin'))
        obj.isAdmin = ApiClient.convertToType(data['isAdmin'], 'Boolean');
      if (data.hasOwnProperty('isSuperAdmin'))
        obj.isSuperAdmin = ApiClient.convertToType(data['isSuperAdmin'], 'Boolean');
    }
    return obj;
  }
}

/**
 * Идентификатор контакта в формате WhatsApp
 * @member {String} id
 */
ResponseChatGroupMetadataParticipants.prototype.id = undefined;

/**
 * Является ли участник администратором
 * @member {Boolean} isAdmin
 */
ResponseChatGroupMetadataParticipants.prototype.isAdmin = undefined;

/**
 * Является ли участник суперадминистратором
 * @member {Boolean} isSuperAdmin
 */
ResponseChatGroupMetadataParticipants.prototype.isSuperAdmin = undefined;

