/*
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ResponseChatGroupMetadata} from './ResponseChatGroupMetadata';

/**
 * The ResponseChat model module.
 * @module model/ResponseChat
 * @version 1.0.0
 */
export class ResponseChat {
  /**
   * Constructs a new <code>ResponseChat</code>.
   * @alias module:model/ResponseChat
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ResponseChat</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResponseChat} obj Optional instance to populate.
   * @return {module:model/ResponseChat} The populated <code>ResponseChat</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ResponseChat();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('isGroup'))
        obj.isGroup = ApiClient.convertToType(data['isGroup'], 'Boolean');
      if (data.hasOwnProperty('isReadOnly'))
        obj.isReadOnly = ApiClient.convertToType(data['isReadOnly'], 'Boolean');
      if (data.hasOwnProperty('unreadCount'))
        obj.unreadCount = ApiClient.convertToType(data['unreadCount'], 'Number');
      if (data.hasOwnProperty('timestamp'))
        obj.timestamp = ApiClient.convertToType(data['timestamp'], 'Number');
      if (data.hasOwnProperty('pinned'))
        obj.pinned = ApiClient.convertToType(data['pinned'], 'Boolean');
      if (data.hasOwnProperty('isMuted'))
        obj.isMuted = ApiClient.convertToType(data['isMuted'], 'Boolean');
      if (data.hasOwnProperty('muteExpiration'))
        obj.muteExpiration = ApiClient.convertToType(data['muteExpiration'], 'Boolean');
      if (data.hasOwnProperty('groupMetadata'))
        obj.groupMetadata = ResponseChatGroupMetadata.constructFromObject(data['groupMetadata']);
    }
    return obj;
  }
}

/**
 * Идентификатор контакта или группы в формате WhatsApp
 * @member {String} id
 */
ResponseChat.prototype.id = undefined;

/**
 * Имя контакта или группы
 * @member {String} name
 */
ResponseChat.prototype.name = undefined;

/**
 * Является ли чат контактом или группой
 * @member {Boolean} isGroup
 */
ResponseChat.prototype.isGroup = undefined;

/**
 * Является ли чат ReadOnly
 * @member {Boolean} isReadOnly
 */
ResponseChat.prototype.isReadOnly = undefined;

/**
 * Количество непрочитанных сообщений в чате
 * @member {Number} unreadCount
 */
ResponseChat.prototype.unreadCount = undefined;

/**
 * Время последней активночти в чате
 * @member {Number} timestamp
 */
ResponseChat.prototype.timestamp = undefined;

/**
 * Является ли чат закрепленным
 * @member {Boolean} pinned
 */
ResponseChat.prototype.pinned = undefined;

/**
 * Выключен ли у чата звук
 * @member {Boolean} isMuted
 */
ResponseChat.prototype.isMuted = undefined;

/**
 * Время, оставшееся до включения звука
 * @member {Boolean} muteExpiration
 */
ResponseChat.prototype.muteExpiration = undefined;

/**
 * @member {module:model/ResponseChatGroupMetadata} groupMetadata
 */
ResponseChat.prototype.groupMetadata = undefined;

