/*
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ResponseChatGroupMetadataParticipants} from './ResponseChatGroupMetadataParticipants';

/**
 * The ResponseChatGroupMetadata model module.
 * @module model/ResponseChatGroupMetadata
 * @version 1.0.0
 */
export class ResponseChatGroupMetadata {
  /**
   * Constructs a new <code>ResponseChatGroupMetadata</code>.
   * Метаданные группы, если чат является группой
   * @alias module:model/ResponseChatGroupMetadata
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ResponseChatGroupMetadata</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResponseChatGroupMetadata} obj Optional instance to populate.
   * @return {module:model/ResponseChatGroupMetadata} The populated <code>ResponseChatGroupMetadata</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ResponseChatGroupMetadata();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('creation'))
        obj.creation = ApiClient.convertToType(data['creation'], 'Number');
      if (data.hasOwnProperty('owner'))
        obj.owner = ApiClient.convertToType(data['owner'], 'String');
      if (data.hasOwnProperty('size'))
        obj.size = ApiClient.convertToType(data['size'], 'Number');
      if (data.hasOwnProperty('participants'))
        obj.participants = ApiClient.convertToType(data['participants'], [ResponseChatGroupMetadataParticipants]);
    }
    return obj;
  }
}

/**
 * Идентификатор группы в формате WhatsApp
 * @member {String} id
 */
ResponseChatGroupMetadata.prototype.id = undefined;

/**
 * Дата создания группы в формате Unix Time Stamp
 * @member {Number} creation
 */
ResponseChatGroupMetadata.prototype.creation = undefined;

/**
 * Идентификатор создателя группы в формате WhatsApp
 * @member {String} owner
 */
ResponseChatGroupMetadata.prototype.owner = undefined;

/**
 * Количество участников в группе
 * @member {Number} size
 */
ResponseChatGroupMetadata.prototype.size = undefined;

/**
 * Массив участников
 * @member {Array.<module:model/ResponseChatGroupMetadataParticipants>} participants
 */
ResponseChatGroupMetadata.prototype.participants = undefined;

