/*
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ResponseAsync model module.
 * @module model/ResponseAsync
 * @version 1.0.0
 */
export class ResponseAsync {
  /**
   * Constructs a new <code>ResponseAsync</code>.
   * @alias module:model/ResponseAsync
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ResponseAsync</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResponseAsync} obj Optional instance to populate.
   * @return {module:model/ResponseAsync} The populated <code>ResponseAsync</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ResponseAsync();
    }
    return obj;
  }
}
// Implement OneOfinlineResponse200Result interface:
