/*
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ResponseMessage model module.
 * @module model/ResponseMessage
 * @version 1.0.0
 */
export class ResponseMessage {
  /**
   * Constructs a new <code>ResponseMessage</code>.
   * @alias module:model/ResponseMessage
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ResponseMessage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResponseMessage} obj Optional instance to populate.
   * @return {module:model/ResponseMessage} The populated <code>ResponseMessage</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ResponseMessage();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('ack'))
        obj.ack = ApiClient.convertToType(data['ack'], 'Number');
      if (data.hasOwnProperty('hasMedia'))
        obj.hasMedia = ApiClient.convertToType(data['hasMedia'], 'Boolean');
      if (data.hasOwnProperty('mediaKey'))
        obj.mediaKey = ApiClient.convertToType(data['mediaKey'], 'String');
      if (data.hasOwnProperty('body'))
        obj.body = ApiClient.convertToType(data['body'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('timestamp'))
        obj.timestamp = ApiClient.convertToType(data['timestamp'], 'Number');
      if (data.hasOwnProperty('from'))
        obj.from = ApiClient.convertToType(data['from'], 'String');
      if (data.hasOwnProperty('to'))
        obj.to = ApiClient.convertToType(data['to'], 'String');
      if (data.hasOwnProperty('isForwarded'))
        obj.isForwarded = ApiClient.convertToType(data['isForwarded'], 'Boolean');
    }
    return obj;
  }
}

/**
 * Идентификатор сообщения
 * @member {String} id
 */
ResponseMessage.prototype.id = undefined;

/**
 * Флаг просмотра сообщения
 * @member {Number} ack
 */
ResponseMessage.prototype.ack = undefined;

/**
 * Флаг, имеет ли сообщение медиафайл
 * @member {Boolean} hasMedia
 */
ResponseMessage.prototype.hasMedia = undefined;

/**
 * Ключ медиафайла (при наличии)
 * @member {String} mediaKey
 */
ResponseMessage.prototype.mediaKey = undefined;

/**
 * Текст сообщения
 * @member {String} body
 */
ResponseMessage.prototype.body = undefined;

/**
 * Тип сообщения
 * @member {String} type
 */
ResponseMessage.prototype.type = undefined;

/**
 * Время сообщения в формате Unix Timestamp
 * @member {Number} timestamp
 */
ResponseMessage.prototype.timestamp = undefined;

/**
 * Идентификатор отправителя в формате WhatsApp
 * @member {String} from
 */
ResponseMessage.prototype.from = undefined;

/**
 * Идентификатор получателя в формате WhatsApp
 * @member {String} to
 */
ResponseMessage.prototype.to = undefined;

/**
 * Флаг, было ли сообщение перенаправлено
 * @member {Boolean} isForwarded
 */
ResponseMessage.prototype.isForwarded = undefined;

// Implement OneOfinlineResponse200Result interface:
