/*
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SeenBody model module.
 * @module model/SeenBody
 * @version 1.0.0
 */
export class SeenBody {
  /**
   * Constructs a new <code>SeenBody</code>.
   * @alias module:model/SeenBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SeenBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SeenBody} obj Optional instance to populate.
   * @return {module:model/SeenBody} The populated <code>SeenBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SeenBody();
      if (data.hasOwnProperty('WhatsappID'))
        obj.whatsappID = ApiClient.convertToType(data['WhatsappID'], 'String');
      if (data.hasOwnProperty('recipient'))
        obj.recipient = ApiClient.convertToType(data['recipient'], Object);
    }
    return obj;
  }
}

/**
 * Идентификатор Whatsapp ID
 * @member {String} whatsappID
 */
SeenBody.prototype.whatsappID = undefined;

/**
 * @member {Object} recipient
 */
SeenBody.prototype.recipient = undefined;

