/*
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The SendBody model module.
 * @module model/SendBody
 * @version 1.0.0
 */
export class SendBody {
  /**
   * Constructs a new <code>SendBody</code>.
   * @alias module:model/SendBody
   * @class
   * @param whatsappID {String} Service Whatsapp ID
   */
  constructor(whatsappID) {
    this.whatsappID = whatsappID;
  }

  /**
   * Constructs a <code>SendBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SendBody} obj Optional instance to populate.
   * @return {module:model/SendBody} The populated <code>SendBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SendBody();
      if (data.hasOwnProperty('WhatsappID'))
        obj.whatsappID = ApiClient.convertToType(data['WhatsappID'], 'String');
      if (data.hasOwnProperty('async'))
        obj.async = ApiClient.convertToType(data['async'], 'Boolean');
      if (data.hasOwnProperty('recipient'))
        obj.recipient = ApiClient.convertToType(data['recipient'], Object);
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], Object);
    }
    return obj;
  }
}

/**
 * Service Whatsapp ID
 * @member {String} whatsappID
 */
SendBody.prototype.whatsappID = undefined;

/**
 * Async query returns Message Object
 * @member {Boolean} async
 */
SendBody.prototype.async = undefined;

/**
 * @member {Object} recipient
 */
SendBody.prototype.recipient = undefined;

/**
 * @member {Object} message
 */
SendBody.prototype.message = undefined;

