/*
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiWhatsgateru);
  }
}(this, function(expect, ApiWhatsgateru) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('MessageMedia', function() {
      beforeEach(function() {
        instance = new ApiWhatsgateru.MessageMedia();
      });

      it('should create an instance of MessageMedia', function() {
        // TODO: update the code to test MessageMedia
        expect(instance).to.be.a(ApiWhatsgateru.MessageMedia);
      });

      it('should have the property body (base name: "body")', function() {
        // TODO: update the code to test the property body
        expect(instance).to.have.property('body');
        // expect(instance.body).to.be(expectedValueLiteral);
      });

      it('should have the property quote (base name: "quote")', function() {
        // TODO: update the code to test the property quote
        expect(instance).to.have.property('quote');
        // expect(instance.quote).to.be(expectedValueLiteral);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

      it('should have the property media (base name: "media")', function() {
        // TODO: update the code to test the property media
        expect(instance).to.have.property('media');
        // expect(instance.media).to.be(expectedValueLiteral);
      });

    });
  });

}));
