/*
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiWhatsgateru);
  }
}(this, function(expect, ApiWhatsgateru) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ResponseMessage', function() {
      beforeEach(function() {
        instance = new ApiWhatsgateru.ResponseMessage();
      });

      it('should create an instance of ResponseMessage', function() {
        // TODO: update the code to test ResponseMessage
        expect(instance).to.be.a(ApiWhatsgateru.ResponseMessage);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property ack (base name: "ack")', function() {
        // TODO: update the code to test the property ack
        expect(instance).to.have.property('ack');
        // expect(instance.ack).to.be(expectedValueLiteral);
      });

      it('should have the property hasMedia (base name: "hasMedia")', function() {
        // TODO: update the code to test the property hasMedia
        expect(instance).to.have.property('hasMedia');
        // expect(instance.hasMedia).to.be(expectedValueLiteral);
      });

      it('should have the property mediaKey (base name: "mediaKey")', function() {
        // TODO: update the code to test the property mediaKey
        expect(instance).to.have.property('mediaKey');
        // expect(instance.mediaKey).to.be(expectedValueLiteral);
      });

      it('should have the property body (base name: "body")', function() {
        // TODO: update the code to test the property body
        expect(instance).to.have.property('body');
        // expect(instance.body).to.be(expectedValueLiteral);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

      it('should have the property timestamp (base name: "timestamp")', function() {
        // TODO: update the code to test the property timestamp
        expect(instance).to.have.property('timestamp');
        // expect(instance.timestamp).to.be(expectedValueLiteral);
      });

      it('should have the property from (base name: "from")', function() {
        // TODO: update the code to test the property from
        expect(instance).to.have.property('from');
        // expect(instance.from).to.be(expectedValueLiteral);
      });

      it('should have the property to (base name: "to")', function() {
        // TODO: update the code to test the property to
        expect(instance).to.have.property('to');
        // expect(instance.to).to.be(expectedValueLiteral);
      });

      it('should have the property isForwarded (base name: "isForwarded")', function() {
        // TODO: update the code to test the property isForwarded
        expect(instance).to.have.property('isForwarded');
        // expect(instance.isForwarded).to.be(expectedValueLiteral);
      });

    });
  });

}));
