/*
 * API whatsgate.ru
 * Интерфейс для взаимодействия с клиентом Whatsapp
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiWhatsgateru);
  }
}(this, function(expect, ApiWhatsgateru) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ResponseChatGroupMetadataParticipants', function() {
      beforeEach(function() {
        instance = new ApiWhatsgateru.ResponseChatGroupMetadataParticipants();
      });

      it('should create an instance of ResponseChatGroupMetadataParticipants', function() {
        // TODO: update the code to test ResponseChatGroupMetadataParticipants
        expect(instance).to.be.a(ApiWhatsgateru.ResponseChatGroupMetadataParticipants);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property isAdmin (base name: "isAdmin")', function() {
        // TODO: update the code to test the property isAdmin
        expect(instance).to.have.property('isAdmin');
        // expect(instance.isAdmin).to.be(expectedValueLiteral);
      });

      it('should have the property isSuperAdmin (base name: "isSuperAdmin")', function() {
        // TODO: update the code to test the property isSuperAdmin
        expect(instance).to.have.property('isSuperAdmin');
        // expect(instance.isSuperAdmin).to.be(expectedValueLiteral);
      });

    });
  });

}));
